account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('edit/', views.profile_edit, name="edit"),
    path('education/', views.education_edit, name="education"),
    path('article/', views.ArticleCreateView.as_view(), name="article"),
    path('article/list/', views.ArticleListView.as_view(), name="article_list"),
    path('article/<int:id>/', views.ArticleShowView.as_view(), name="article_show"),
    path('articles/', views.UserArticleListView.as_view(), name="user_articles"),
    path('article/edit/<int:id>', views.ArticleUpdateView.as_view(), name="article_edit"),
    path('ticket/add/', views.ticket_add, name='ticket_add'),

    path('judgement/list/', views.JudgementListView.as_view(), name="judgement_list"),
    path('judgement/status', views.ArticleListJudgementStatus.as_view(), name="judgement_status"),
    path('judgement/referee/<int:id>/', views.JudgementRefereeView.as_view(), name="judgement_referee"),
    path('assistant/list/', views.JudgementAssistantListView.as_view(), name="assistant_list"),
    path('judgement/assistant/<int:id>/', views.JudgementAssistantView.as_view(), name="judgement_assistant"),
    path('judge/list/', views.JudgementJudgeListView.as_view(), name="judge_list"),
    path('judge/<int:id>/', views.JudgementJudgeView.as_view(), name="judge"),
    path('export_to_excel/', views.export_to_excel, name='export'),

    path('arbitration/<int:id>/', views.ArbitrationShowView.as_view(), name='arbitration')
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # Post views
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('gallery/1/', views.gallery_first, name='gallery_first'),
    path('gallery/2/', views.gallery_second, name='gallery_second'),
    path('gallery/3/', views.gallery_third, name='gallery_third'),
    path('farakhan/', views.farakhan, name='farakhan'),
    path('about/', views.about, name='about'),
    path('olom_payeh/', views.olom_payeh, name='olom_payeh'),
    path('olom_ensani/', views.olom_ensani, name='olom_ensani'),
    path('fani/', views.fani, name='fani'),
    path('keshavarzi/', views.keshavarzi, name='keshavarzi'),
    path('pezeshki/', views.pezeshki, name='pezeshki'),
    path('dampezeshki/', views.dampezeshki, name='dampezeshki'),
    path('honar/', views.honar, name='honar'),
    path('introduction/', views.introduction, name='introduction'),
    path('foundation/', views.foundation, name='foundation'),
    path('purpose/', views.PurposeView.as_view(), name='purpose'),
    path('executive/', views.executive, name='executive'),
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('<int:id>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    # path('<int:post_id>/share/',
    #      views.post_share, name='post_share'),
    # path('<int:post_id>/comment/',
    #      views.post_comment, name='post_comment'),
]

festival/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django_jalali.db import models as jmodels
from extentions.utils import covert_to_jalali


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                      .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    class Category(models.TextChoices):
        DEFAULT = 'DF', 'پیش فرض'
        IMPORTANT = 'IM', 'اخبار مهم'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish',
                            allow_unicode=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    lead = models.TextField()
    body = RichTextField()
    views = models.PositiveIntegerField(default=0)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    category = models.CharField(max_length=2,
                              choices=Category.choices,
                              default=Category.DEFAULT)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/',
                              blank=True)

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title
    
    # show jalali publish date string
    def j_publish(self):
        return covert_to_jalali(self.publish)

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.id,
                             self.slug])

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import ListView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Post

class HomeView(View):
    def get(self, request):
        posts = Post.published.all().order_by('-publish')
        paginator = Paginator(posts, 8)
        page = request.GET.get('page', 1)
    
        try:
            result = paginator.page(page)
        except PageNotAnInteger:
            result = paginator.page(1)
        except EmptyPage:
            result = paginator.page(paginator.num_pages)

        banner = posts.filter(category="IM")[:4]
        return render(request, 'blog/home.html', {'posts': result, 'banner': banner})


def gallery_first(request):
    return render(request, 'blog/post/gallery1.html')

def gallery_second(request):
    return render(request, 'blog/post/gallery2.html')

def gallery_third(request):
    return render(request, 'blog/post/gallery3.html')

def farakhan(request):
    return render(request, 'blog/post/farakhan.html')

def about(request):
    return render(request, 'blog/post/about.html')

def olom_payeh(request):
    return render(request, 'blog/post/olom_payeh.html')

def olom_ensani(request):
    return render(request, 'blog/post/olom_ensani.html')

def fani(request):
    return render(request, 'blog/post/fani.html')

def pezeshki(request):
    return render(request, 'blog/post/pezeshki.html')

def keshavarzi(request):
    return render(request, 'blog/post/keshavarzi.html')

def dampezeshki(request):
    return render(request, 'blog/post/dampezeshki.html')

def honar(request):
    return render(request, 'blog/post/honar.html')

def introduction(request):
    return render(request, 'blog/post/introduction.html')

def executive(request):
    return render(request, 'blog/post/executive.html')


class PurposeView(View):
    def get(self, request):
        posts = Post.published.all()[:5]
        return render(request, 'blog/post/purpose.html', {'posts': posts})

def foundation(request):
    return render(request, 'blog/post/foundation.html')

class NewsListView(View):
    def get(self, request):
        posts = Post.published.all().order_by('-publish')
        paginator = Paginator(posts, 12)
        page = request.GET.get('page', 1)
    
        try:
            result = paginator.page(page)
        except PageNotAnInteger:
            result = paginator.page(1)
        except EmptyPage:
            result = paginator.page(paginator.num_pages)
        return render(request, 'blog/post/news_list.html', {'posts': result})


def news(request):
    return render(request, 'blog/post/news_list.html')

def post_detail(request, id, post):
    posts = Post.published.all()[:5]
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             id=id)
    post.views += 1
    post.save()
    return render(request,
                  'blog/post/news_detail.html',
                  {'post': post, 'posts': posts})

class PostListView(ListView):
    """
    Alternative post list view
    """
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

templates/blog/_carousel.html
{% load static %}


    <!-- Swiper -->
     <div class="swiper mySwiper">
        <div class="swiper-wrapper">
          <!-- <div class="swiper-slide"><a href={% url "blog:farakhan" %}><img src={% static "img/banner3.jpg" %}></img></a></div> -->
          <div class="swiper-slide bg-cover" style="background-image: url({% static 'img/banner2.jpg' %})">
            <div class="absolute bottom-5 bg-white object-bottom bg-opacity-60 shadow-lg w-full px-2 py-1">
                <h1 class="p-9 text-2xl text-primary-950 font-bold">فراخوان افتتاح جشنواره امیر کبیر</h1>
            </div>
          </div>
          {% for post in banner %}
            <div class="swiper-slide bg-cover" style="background-image: url({{ post.photo.url }})">
                <div class="absolute bottom-5 bg-white object-bottom bg-opacity-60 shadow-lg w-full px-2 py-1">
                    <a href={{ post.get_absolute_url }}><h1 class="p-9 text-2xl text-primary-950 font-bold">{{ post.title }}</h1></a>
                </div>
            </div>
          {% endfor %}
        </div>
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-pagination"></div>
      </div>
      <!-- Swiper JS -->

templates/blog/_customer.html
{% load static %}
<section class="dark:bg-gray-900">
    <div class="py-8 lg:py-16 mx-auto max-w-screen-xl px-4">
        <h2 class="mb-8 lg:mb-16 text-3xl font-extrabold tracking-tight leading-tight text-center text-primary-950 dark:text-white md:text-4xl">حامیان</h2>
        <div class="grid grid-cols-2 gap-8 text-gray-500 sm:gap-12 grid-cols-4 dark:text-gray-400">
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/ACECR_logo.png' %}" alt="">                                                               
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/logo-otagh.png' %}" alt="">                                               
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/bonyad-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/acecr_culture.png' %}" alt="">                       
            </a>
            
            
        </div>

        <div class="grid grid-cols-2 mt-6 gap-8 text-gray-500 grid-cols-8 dark:text-gray-400">
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/shahrdari-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/olom-pezeshki-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/khu_logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/azad-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/ostandari-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/shora-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/nashr-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/pardis-logo.png' %}" alt="">                                                                                   
            </a>
        </div>
        <div class="grid grid-cols-2 mt-6 gap-8 text-gray-500 grid-cols-8 dark:text-gray-400">
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/tejari-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/sanat-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/park-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/payam-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/razi-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/shahrak-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/barname-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/otagh-iran-logo.png' %}" alt="">                                                                                   
            </a>
        </div>
        <div class="grid grid-cols-2 mt-6 gap-8 text-gray-500 grid-cols-8 dark:text-gray-400">
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/razi-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/taavon-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/estandard-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/otagh-pajohesh-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/jahad-keshavarzi-logo.png' %}" alt="">                                                                                   
            </a>
        </div>

        
    </div>
</section>

templates/blog/_gallery.html
{% load static %}
<section class="dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16 lg:px-6">
        <div class="mx-auto mb-8 max-w-screen-sm lg:mb-16">
            <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-primary-950 dark:text-white">گزارش تصویری</h2>
            {% comment %} <p class="font-light text-gray-500 sm:text-xl dark:text-gray-400"></p> {% endcomment %}
        </div> 
        <div class="grid gap-8 lg:gap-16 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3">    
            <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
                <a href="#">
                    <img class="rounded-t-lg" src="{% static 'img/gallery3/image (1).jpg' %}" alt="" />
                </a>
                <div class="p-2">
                    <a href="#">
                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">آیین پایانی اولین جشنواره ملی امیرکبیر</h5>
                    </a>
                    <a href={% url "blog:gallery_third" %} class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        بیشتر
                        <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                        </svg>
                    </a>
                </div>
            </div>
            <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
                <a href="#">
                    <img class="rounded-t-lg" src="{% static 'img/gallery2/image (1).jpg' %}" alt="" />
                </a>
                <div class="p-2">
                    <a href="#">
                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">آیین پایانی دومین جشنواره ملی امیرکبیر</h5>
                    </a>
                    <a href={% url "blog:gallery_second" %} class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        بیشتر
                        <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                        </svg>
                    </a>
                </div>
            </div>
            <div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
                <a href="#">
                    <img class="rounded-t-lg" src="{% static 'img/gallery1/image-(1).jpg' %}" alt="" />
                </a>
                <div class="p-2">
                    <a href="#">
                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">آیین پایانی سومین جشنواره ملی امیرکبیر</h5>
                    </a>
                    <a href={% url "blog:gallery_first" %} class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        بیشتر
                        <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                        </svg>
                    </a>
                </div>
            </div>

        </div>  
    </div>
  </section>

templates/blog/_navbar.html
{% load static %}
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
  <a href={% url 'main' %} class="flex items-center space-x-3 rtl:space-x-reverse">
      <img src="{% static 'img/logo-wide.png' %}" class="h-16" alt="amirkabirfestival logo" />
  </a>
  <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
      <button type="button" class="text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"><a href={% url "account:login" %}>ثبت نام / ورود</a></button>
      <button data-collapse-toggle="navbar-cta" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-cta" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>
  </div>
  <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-cta">
    <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
      <li>
        <a href={% url 'main' %} class="block py-2 px-3 md:p-0 text-white bg-primary-700 rounded md:bg-transparent md:text-primary-700 md:dark:text-primary-500" aria-current="page">خانه</a>
      </li>
      <li>
        <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar" class="flex items-center justify-between w-full py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:w-auto dark:text-white md:dark:hover:text-blue-500 dark:focus:text-white dark:border-gray-700 dark:hover:bg-gray-700 md:dark:hover:bg-transparent">جشنواره 
          
        </button>
        <!-- Dropdown menu -->
        <div id="dropdownNavbar" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
            <ul class="py-2 text-sm text-gray-700 dark:text-gray-400" aria-labelledby="dropdownLargeButton">
              <li>
                <a href="{% url "blog:purpose" %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">اهداف</a>
              </li>
              <li>
                <a href="{% url "blog:executive" %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">برنامه اجرایی</a>
              </li>
              <li>
                <a href="{% url "blog:foundation" %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">محورهای جشنواره</a>
              </li>
              <li>
                <a href="{% url "blog:purpose" %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">معرفی</a>
              </li>
        </div>
      </li>
      <li>
        <button id="dropdownNavbarLink1" data-dropdown-toggle="dropdownNavbar1" class="flex items-center justify-between w-full py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:w-auto dark:text-white md:dark:hover:text-blue-500 dark:focus:text-white dark:border-gray-700 dark:hover:bg-gray-700 md:dark:hover:bg-transparent">گروه های آموزشی 
        </button>
        <!-- Dropdown menu -->
        <div id="dropdownNavbar1" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
            <ul class="py-2 text-sm text-gray-700 dark:text-gray-400" aria-labelledby="dropdownLargeButton">
              <li>
                <a href="{% url "blog:olom_ensani" %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">علوم انسانی و زبان های خارجه</a>
              </li>
              <li>
                <a href="{% url "blog:olom_payeh" %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">علوم پایه</a>
              </li>
              <li>
                <a href="{% url "blog:fani" %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">فنی و مهندسی</a>
              </li>
              <li>
                <a href="{% url "blog:keshavarzi" %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">کشاورزی، منابع طبیعی و محیط زیست</a>
              </li>
              <li>
                <a href="{% url "blog:pezeshki" %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"> علوم پزشکی </a>
              </li>
              <li>
                <a href="{% url "blog:dampezeshki" %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">دامپزشکی و علوم دامی </a>
              </li>
              <li>
                <a href="{% url "blog:honar" %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">هنر و معماری </a>
              </li>
        </div>
      </li>
      <li>
        <a href="#" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-primary-700 md:dark:hover:text-primary-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">حامیان</a>
      </li>
      <li>
        <a href={% url "blog:about" %} class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-primary-700 md:dark:hover:text-primary-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">دبیرخانه جشنواره</a>
      </li>
     
    </ul>
  </div>
  </div>
</nav>

templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html dir="rtl" lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>جشنواره ملی امیرکبیر</title>

    <link rel="stylesheet" href="{% static 'css/amirkabir-ui.css' %}">

</head>

<body class="bg-green-50">
    {% include 'blog/main/_navbar.html' %}
    {% include 'blog/main/_hero.html' %}
    {% include 'blog/main/_news.html' %}
    {% include 'blog/main/_gallery.html' %}
    {% block content %}{% endblock content %}
    {% include 'blog/main/_footer.html' %}
  

    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
</body>

</html>

templates/blog/home.html
{% extends 'blog_base.html' %}

{% block content %}
    {% include 'blog/main/_hero.html' %}
    {% include 'blog/main/_news.html' %}
    {% include 'blog/main/_gallery.html' %}
    {% include 'blog/main/_subscriber.html' %}
    {% include 'blog/main/_faq.html' %}
    {% include 'blog/main/_customer.html' %}
{% endblock content %}