account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('edit/', views.profile_edit, name="edit"),
    path('education/', views.education_edit, name="education"),
    path('article/', views.ArticleCreateView.as_view(), name="article"),
    path('article/list/', views.ArticleListView.as_view(), name="article_list"),
    path('article/<int:id>/', views.ArticleShowView.as_view(), name="article_show"),
    path('articles/', views.UserArticleListView.as_view(), name="user_articles"),
    path('article/edit/<int:id>', views.ArticleUpdateView.as_view(), name="article_edit"),
    path('ticket/add/', views.ticket_add, name='ticket_add'),

    path('judgement/list/', views.JudgementListView.as_view(), name="judgement_list"),
    path('judgement/status', views.ArticleListJudgementStatus.as_view(), name="judgement_status"),
    path('judgement/referee/<int:id>/', views.JudgementRefereeView.as_view(), name="judgement_referee"),
    path('assistant/list/', views.JudgementAssistantListView.as_view(), name="assistant_list"),
    path('judgement/assistant/<int:id>/', views.JudgementAssistantView.as_view(), name="judgement_assistant"),
    path('judge/list/', views.JudgementJudgeListView.as_view(), name="judge_list"),
    path('judge/<int:id>/', views.JudgementJudgeView.as_view(), name="judge"),
    path('export_to_excel/', views.export_to_excel, name='export'),

    path('arbitration/<int:id>/', views.ArbitrationShowView.as_view(), name='arbitration')
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # Post views
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('gallery/1/', views.gallery_first, name='gallery_first'),
    path('gallery/2/', views.gallery_second, name='gallery_second'),
    path('gallery/3/', views.gallery_third, name='gallery_third'),
    path('farakhan/', views.farakhan, name='farakhan'),
    path('about/', views.about, name='about'),
    path('olom_payeh/', views.olom_payeh, name='olom_payeh'),
    path('olom_ensani/', views.olom_ensani, name='olom_ensani'),
    path('fani/', views.fani, name='fani'),
    path('keshavarzi/', views.keshavarzi, name='keshavarzi'),
    path('pezeshki/', views.pezeshki, name='pezeshki'),
    path('dampezeshki/', views.dampezeshki, name='dampezeshki'),
    path('honar/', views.honar, name='honar'),
    path('introduction/', views.introduction, name='introduction'),
    path('foundation/', views.foundation, name='foundation'),
    path('purpose/', views.PurposeView.as_view(), name='purpose'),
    path('executive/', views.executive, name='executive'),
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('<int:id>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    # path('<int:post_id>/share/',
    #      views.post_share, name='post_share'),
    # path('<int:post_id>/comment/',
    #      views.post_comment, name='post_comment'),
]

festival/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from blog import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='main'),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django_jalali.db import models as jmodels
from extentions.utils import covert_to_jalali


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                      .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    class Category(models.TextChoices):
        DEFAULT = 'DF', 'پیش فرض'
        IMPORTANT = 'IM', 'اخبار مهم'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish',
                            allow_unicode=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    lead = models.TextField()
    body = RichTextField()
    views = models.PositiveIntegerField(default=0)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    category = models.CharField(max_length=2,
                              choices=Category.choices,
                              default=Category.DEFAULT)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/',
                              blank=True)

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title
    
    # show jalali publish date string
    def j_publish(self):
        return covert_to_jalali(self.publish)

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.id,
                             self.slug])

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import ListView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Post

class HomeView(View):
    def get(self, request):
        posts = Post.published.all().order_by('-publish')
        paginator = Paginator(posts, 8)
        page = request.GET.get('page', 1)
    
        try:
            result = paginator.page(page)
        except PageNotAnInteger:
            result = paginator.page(1)
        except EmptyPage:
            result = paginator.page(paginator.num_pages)

        banner = posts.filter(category="IM")[:4]
        return render(request, 'blog/home.html', {'posts': result, 'banner': banner})


def gallery_first(request):
    return render(request, 'blog/post/gallery1.html')

def gallery_second(request):
    return render(request, 'blog/post/gallery2.html')

def gallery_third(request):
    return render(request, 'blog/post/gallery3.html')

def farakhan(request):
    return render(request, 'blog/post/farakhan.html')

def about(request):
    return render(request, 'blog/post/about.html')

def olom_payeh(request):
    return render(request, 'blog/post/olom_payeh.html')

def olom_ensani(request):
    return render(request, 'blog/post/olom_ensani.html')

def fani(request):
    return render(request, 'blog/post/fani.html')

def pezeshki(request):
    return render(request, 'blog/post/pezeshki.html')

def keshavarzi(request):
    return render(request, 'blog/post/keshavarzi.html')

def dampezeshki(request):
    return render(request, 'blog/post/dampezeshki.html')

def honar(request):
    return render(request, 'blog/post/honar.html')

def introduction(request):
    return render(request, 'blog/post/introduction.html')

def executive(request):
    return render(request, 'blog/post/executive.html')


class PurposeView(View):
    def get(self, request):
        posts = Post.published.all()[:5]
        return render(request, 'blog/post/purpose.html', {'posts': posts})

def foundation(request):
    return render(request, 'blog/post/foundation.html')

class NewsListView(View):
    def get(self, request):
        posts = Post.published.all().order_by('-publish')
        paginator = Paginator(posts, 12)
        page = request.GET.get('page', 1)
    
        try:
            result = paginator.page(page)
        except PageNotAnInteger:
            result = paginator.page(1)
        except EmptyPage:
            result = paginator.page(paginator.num_pages)
        return render(request, 'blog/post/news_list.html', {'posts': result})


def news(request):
    return render(request, 'blog/post/news_list.html')

def post_detail(request, id, post):
    posts = Post.published.all()[:5]
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             id=id)
    post.views += 1
    post.save()
    return render(request,
                  'blog/post/news_detail.html',
                  {'post': post, 'posts': posts})

class PostListView(ListView):
    """
    Alternative post list view
    """
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

templates/blog/main/_customer.html
{% load static %}
<section class="py-12 xl:pt-12 xl:pb-0">
    <div class="container mx-auto bg-white rounded-[10px] shadow-custom1 h-full py-8 px-4 lg:py-16 lg:px-6">
        <div class="flex flex-col items-center h-full pt-12 mb-12">
            <h2 class="mb-4 text-3xl lg:text-4xl -tight font-bold text-primary-950">حامیان</h2>
        </div> 
        <div class="grid grid-cols-2 gap-8 text-gray-500 sm:gap-12 grid-cols-4 dark:text-gray-400">
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/ACECR_logo.png' %}" alt="">                                                               
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/logo-otagh.png' %}" alt="">                                               
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/bonyad-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/acecr_culture.png' %}" alt="">                       
            </a>    
        </div>
        <div class="grid grid-cols-2 mt-6 gap-8 text-gray-500 grid-cols-8 dark:text-gray-400">
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/shahrdari-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/olom-pezeshki-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/khu_logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/azad-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/ostandari-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/shora-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/nashr-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/pardis-logo.png' %}" alt="">                                                                                   
            </a>
        </div>
        <div class="grid grid-cols-2 mt-6 gap-8 text-gray-500 grid-cols-8 dark:text-gray-400">
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/tejari-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/sanat-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/park-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/payam-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/razi-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/shahrak-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/barname-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/otagh-iran-logo.png' %}" alt="">                                                                                   
            </a>
        </div>
        <div class="grid grid-cols-2 mt-6 gap-8 text-gray-500 grid-cols-8 dark:text-gray-400">
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/razi-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/taavon-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/estandard-logo.png' %}" alt="">                                                                                    
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/otagh-pajohesh-logo.png' %}" alt="">                                                                                   
            </a>
            <a href="#" class="flex justify-center items-center">
                <img src="{% static 'img/jahad-keshavarzi-logo.png' %}" alt="">                                                                                   
            </a>
        </div>
    </div>
</section>

templates/blog/main/_footer.html
 {% load static %}
 <footer class="pt-4 pb-2 bg-primary-50 lg:pt-12 ">
    <div class="container mx-auto text-center shadow-custom1 rounded-[10px] bg-white">
        <a href={% url 'main' %} class="flex justify-center items-center text-2xl font-semibold pt-8">
            <img src={% static 'img/logo-wide.png' %} alt="">    
        </a>
        <p class="my-6 text-gray-500 dark:text-gray-400">جشنواره ملی پایان نامه های کاربردی کارفرما محوز</p>
        <ul class="flex flex-wrap justify-center items-center mb-6 text-gray-900 dark:text-white">
            <li>
                <a href="#" class="mr-4 hover:underline md:mr-6 ">خانه</a>
            </li>
            <li>
                <a href="#" class="mr-4 hover:underline md:mr-6">درباره ما</a>
            </li>
            <li>
                <a href="#" class="mr-4 hover:underline md:mr-6 ">اخبار</a>
            </li>
            </li>
        </ul>
        <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">طراحی و توسعه توسط SMRHA</span>
    </div>
  </footer>

templates/blog/main/_gallery.html
{% load static %}
<section class="py-12 xl:pt-12 xl:pb-0">
    <div class="container mx-auto h-full py-8 px-4 lg:py-16 lg:px-6">
        <div class="flex flex-col items-center h-full pt-12 mb-12">
            <h2 class="mb-4 text-3xl lg:text-4xl -tight font-bold text-primary-950">گزارش تصویری</h2>
            <p class="font-light text-gray-500 sm:text-xl">گزارش های تصویری جشنواره پایان نامه های کاربردی و کارفرمایی امیرکبیر</p>
        </div> 
        <div class="grid gap-8 lg:gap-8 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3">    
            <div class="max-w-sm p-2 bg-white border rounded-lg">
                <a href={% url "blog:gallery_third" %}>
                    <img class="rounded-2xl shadow-custom1" src="{% static 'img/gallery3/image (1).jpg' %}" alt="" />
                </a>
                <div class="flex gap-x-4 pt-1 pb-0 text-sm">
                    <time class="hover:bg-primary-200 p-2 rounded-full" datetime="2020-03-16">1 تیر 1403</time>
                    <a class="hover:bg-primary-200 p-2 rounded-full" href="#">اخبار تصویری</a>
                </div>
                <div class="p-2">
                    <a href={% url "blog:gallery_third" %}>
                        <h5 class="mb-4 font-semibold text-gray-900">آیین پایانی اولین جشنواره ملی امیرکبیر</h5>
                    </a>
                    <a href={% url "blog:gallery_third" %} class="inline-flex items-center px-3 py-2 text-sm font-medium text-center rounded-full btn-outline">
                        بیشتر
                        <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                        </svg>
                    </a>
                </div>
            </div>
            <div class="max-w-sm p-2 bg-white border rounded-lg">
                <a href={% url "blog:gallery_second" %}>
                    <img class="rounded-2xl shadow-custom1" src="{% static 'img/gallery2/image (1).jpg' %}" alt="" />
                </a>
                <div class="flex gap-x-4 pt-1 pb-0 text-sm">
                    <time class="hover:bg-primary-200 p-2 rounded-full" datetime="2020-03-16">1 تیر 1403</time>
                    <a class="hover:bg-primary-200 p-2 rounded-full" href="#">اخبار تصویری</a>
                </div>
                <div class="p-2">
                    <a href={% url "blog:gallery_second" %}>
                        <h5 class="mb-4 font-semibold text-gray-900">آیین پایانی دومین جشنواره ملی امیرکبیر</h5>
                    </a>
                    <a href={% url "blog:gallery_second" %} class="inline-flex items-center px-3 py-2 text-sm font-medium text-center rounded-full btn-outline">
                        بیشتر
                        <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                        </svg>
                    </a>
                </div>
            </div>
            <div class="max-w-sm p-2 bg-white border rounded-xl">
                <a href={% url "blog:gallery_first" %}>
                    <img class="rounded-2xl shadow-custom1" src="{% static 'img/gallery1/image (1).jpg' %}" alt="" />
                </a>
                <div class="flex gap-x-4 pt-1 pb-0 text-sm">
                    <time class="hover:bg-primary-200 p-2 rounded-full" datetime="2020-03-16">1 تیر 1403</time>
                    <a class="hover:bg-primary-200 p-2 rounded-full" href="#">اخبار تصویری</a>
                </div>
                <div class="p-2">
                    <a href={% url "blog:gallery_first" %}>
                        <h5 class="mb-4 font-semibold text-gray-900">آیین پایانی سومین جشنواره ملی امیرکبیر</h5>
                    </a>
                    <a href={% url "blog:gallery_first" %} class="inline-flex items-center px-3 py-2 text-sm font-medium text-center rounded-full btn-outline">
                        بیشتر
                        <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
                        </svg>
                    </a>
                </div>
            </div>

        </div>  
    </div>
</section>

templates/blog/main/_navbar.html
{% load static %}
<header class="bg-primary-50 py-8 lg:pt-6 lg:pb-14">
    <div class="container mx-auto lg:relative flex flex-col lg:flex-row lg:justify-between gap-y-4 lg:gap-y-8">
        <div class="flex justify-center lg:justify-normal">
            <a href={% url 'main' %}>
                <img src="{% static 'img/logo-wide.png' %}" alt="">
            </a>
        </div>
        <div class="flex flex-col gap-y-4 lg:flex-row lg:gap-x-10 lg:gap-y-0 lg:items-center">
            <!-- Location -->
            <div class="flex justify-center items-center gap-x-2 lg:justify-normal">
                <i class="ri-map-pin-2-fill text-2xl text-primary-500"></i>
                <div>استان البرز، کرج، عظیمیه، میدان مهران، نبش ندای جنوبی</div>
            </div>
            <!-- Phone -->
            <div class="flex justify-center items-center gap-x-2 lg:justify-normal">
                <i class="ri-phone-fill text-2xl text-primary-500"></i>
                <div class="text-secondary">02632521124</div>
            </div>
            <!-- btn -->
            <a href={% url 'account:login' %} class="btn btn-sm btn-outline w-[240px] lg:w-auto lg:mx-0">ورود / ثبت نام</a>
            <!-- mobile nav -->
            <nav class="mnav bg-white fixed w-[300px] top-0 -left-[300px] h-screen shadow-2xl lg:hidden transition-all duration-300 z-20">
                <!-- nav trigger btn -->
                <div class="mnav__close-btn bg-primary w-8 h-8 relative -right-full top-8
                    flex justify-center items-center rounded-tr-lg rounded-br-lg cursor-pointer transition-all">
                <i class="mnav__close-btn-icon ri-arrow-right-s-line text-2xl text-white"></i>
                </div>
                <!-- logo, list, form -->
                <div class="px-12 flex flex-col gap-y-12 h-full">
                <!-- logo -->
                <a href="#">
                    <img src={% static 'img/logo-wide.png' %} alt="">
                </a>
                <!-- list -->
                <ul class="flex flex-col gap-y-5">
                <li>
                    <a 
                    href="#"
                    class="text-secondary hover:text-accent transition-all duration-300">
                    جشنواره
                    </a>
                </li>
                <li>
                    <a 
                    href="#"
                    class="text-secondary hover:text-accent transition-all duration-300">
                    Doctors
                    </a>
                </li>
                <li>
                    <a 
                    href="#"
                    class="text-secondary hover:text-accent transition-all duration-300">
                    Department
                    </a>
                </li>
                <li>
                    <a 
                    href="#"
                    class="text-secondary hover:text-accent transition-all duration-300">
                    Servives
                    </a>
                </li>
                <li>
                    <a 
                    href="#"
                    class="text-secondary hover:text-accent transition-all duration-300">
                    Blog
                    </a>
                </li>
                <li>
                    <a 
                    href="#"
                    class="text-secondary hover:text-accent transition-all duration-300">
                    Contact
                    </a>
                </li>
                </ul>
                <!-- form -->
                <form class="relative flex gap-x-[10px]">
                    <label for="mnav-search-input">
                    <i class="ri-search-line text-2xl text-accent"></i>
                    </label>
                    <input 
                    type="text" 
                    id="mnav-search-input"
                    placeholder="Search ..."
                    class="outline-none w-[160px border-b-2 focus:border-accent placeholder:italic"
                    />
                </form>
                </div>
            </nav>
        </div>
        <!-- desktop nav -->
        <nav class="bg-white absolute w-full left-0 -bottom-[86px] shadow-custom1 h-16 rounded-[10px] hidden z-50 lg:flex lg:items-center lg:justify-between lg:px-[50px]">
            <!-- list -->
            <div>
                <ul class="flex gap-x-4">
                    <li>
                        <a 
                        href={% url 'main' %}
                        class="text-secondary hover:text-accent transition-all duration-300">
                        خانه
                        </a>
                    </li>
                    <li>
                        <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar" class="flex items-center justify-between w-full py-2 px-3 text-secondary  hover:text-accent md:hover:bg-transparent md:border-0 md:hover:text-accent-secondary md:p-0 md:w-auto">
                            جشنواره          
                        </button>
                        <!-- Dropdown menu -->
                        <div id="dropdownNavbar" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 w-44 shadow-custom1">
                            <ul class="py-2 text-sm text-secondary aria-labelledby="dropdownLargeButton">
                              <li>
                                <a href="{% url "blog:purpose" %}" class="block px-4 py-2 hover:text-accent transition-all duration-300">اهداف</a>
                              </li>
                              <li>
                                <a href="{% url "blog:executive" %}" class="block px-4 py-2 hover:text-accent transition-all duration-300">برنامه اجرایی</a>
                              </li>
                              <li>
                                <a href="{% url "blog:foundation" %}" class="block px-4 py-2 hover:text-accent transition-all duration-300">محورهای جشنواره</a>
                              </li>
                              <li>
                                <a href="{% url "blog:purpose" %}" class="block px-4 py-2 hover:text-accent transition-all duration-300">معرفی</a>
                              </li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <button id="dropdownNavbarLink1" data-dropdown-toggle="dropdownNavbar1" class="flex items-center justify-between w-full py-2 px-3 text-secondary  hover:text-accent md:hover:bg-transparent md:border-0 md:hover:text-accent-secondary md:p-0 md:w-auto">
                            گروه های آموزشی          
                        </button>
                        <!-- Dropdown menu -->
                        <div id="dropdownNavbar1" class="z-20 hidden font-normal bg-white divide-y divide-gray-100 w-44 shadow-custom1">
                            <ul class="py-2 text-sm text-secondary aria-labelledby="dropdownLargeButton">
                                <li>
                                    <a href="{% url "blog:olom_ensani" %}" class="block px-4 py-2 hover:text-accent transition-all duration-300">علوم انسانی و زبان های خارجه</a>
                                  </li>
                                  <li>
                                    <a href="{% url "blog:olom_payeh" %}" class="block px-4 py-2 hover:text-accent transition-all duration-300">علوم پایه</a>
                                  </li>
                                  <li>
                                    <a href="{% url "blog:fani" %}" class="block px-4 py-2 hover:text-accent transition-all duration-300">فنی و مهندسی</a>
                                  </li>
                                  <li>
                                    <a href="{% url "blog:keshavarzi" %}" class="block px-4 py-2 hover:text-accent transition-all duration-300">کشاورزی، منابع طبیعی و محیط زیست</a>
                                  </li>
                                  <li>
                                    <a href="{% url "blog:pezeshki" %}" class="block px-4 py-2 hover:text-accent transition-all duration-300"> علوم پزشکی </a>
                                  </li>
                                  <li>
                                    <a href="{% url "blog:dampezeshki" %}" class="block px-4 py-2 hover:text-accent transition-all duration-300">دامپزشکی و علوم دامی </a>
                                  </li>
                                <li>
                                <a href="{% url "blog:honar" %}" class="block px-4 py-2 hover:text-accent transition-all duration-300">هنر و معماری </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <a 
                        href="{% url 'blog:news_list' %}"
                        class="border-r pr-4 text-secondary hover:text-accent transition-all duration-300">
                        اخبار
                        </a>
                    </li>
                    <li>
                        <a 
                        href="#"
                        class="border-r pr-4 text-secondary hover:text-accent transition-all duration-300">
                        حامیان
                        </a>
                    </li>
                    <li>
                        <a 
                        href="#"
                        class="border-r pr-4 text-secondary hover:text-accent transition-all duration-300">
                        دبیرخانه جشنواره
                        </a>
                    </li>
                    </ul>
            </div>
        </nav> 
    </div>
</header>